### ISSUE TITLE
Remove Sync trait bound for create_datareader, AnyDataReaderListener impl

### ISSUE THREAD

**Issue by samcarey** [s2e-systems/dust-dds#186]
I needed to create a DataReader with a listener that holds a `Box<dyn SerialPort>` as returned from [this function](https://docs.rs/serialport/latest/serialport/struct.SerialPortBuilder.html#method.open) (SerialPort implies Send but not Sync). At first I couldn't because the [create_datareader](https://github.com/s2e-systems/dust-dds/blob/e54e54df2fdcd971250de28b64dce03f2c56b7b9/dds/src/dds/subscription/subscriber.rs#L96) function requires the listener trait object to be Sync. Then I tried deleting the Sync bound in my local patch of dust_dds, which required also removing it from [this AnyDataReaderListener impl](https://github.com/s2e-systems/dust-dds/blob/e54e54df2fdcd971250de28b64dce03f2c56b7b9/dds/src/implementation/dds/any_data_reader_listener.rs#L37C58-L37C58). Then dust_dds and my project compiled and ran fine with the SerialPort listener.

Is there a good reason for this bound or could it be removed?

If it could be removed in this case, there may be other similar cases in the code base that it could be removed as well.

**Comment by jrebelo** [comment]
The Sync trait bound is a leftover from a previous implementation of the DustDDS internals. I have prepared a PR to remove it. 

Since you are using the DataReaderListener can I ask you if you are making use of the provided DataReader object to access the data like what is done for example here: https://github.com/s2e-systems/dust-dds/blob/e54e54df2fdcd971250de28b64dce03f2c56b7b9/dds/examples/best_effort_subscriber.rs#L34

We are currently reviewing the listener architecture and we try to collect information on some external use cases.

**Comment by ari-github** [comment]
> The Sync trait bound is a leftover from a previous implementation of the DustDDS internals. I have prepared a PR to remove it.
> 
> Since you are using the DataReaderListener can I ask you if you are making use of the provided DataReader object to access the data like what is done for example here:
> 
> https://github.com/s2e-systems/dust-dds/blob/e54e54df2fdcd971250de28b64dce03f2c56b7b9/dds/examples/best_effort_subscriber.rs#L34
> 
> We are currently reviewing the listener architecture and we try to collect information on some external use cases.

I do.
