### ISSUE TITLE
DurationKind incompatible with json, ron deserialization

### ISSUE THREAD

**Issue by samcarey** [s2e-systems/dust-dds#188]
I'm trying to save/load some QoS parameters in a text file for configuration purposes. I noticed that `DurationKind` [has a custom Serialize/Deserialize impl](https://github.com/s2e-systems/dust-dds/blob/e54e54df2fdcd971250de28b64dce03f2c56b7b9/dds/src/dds/infrastructure/time.rs#L12) that is causing issues when trying to deserialize it from a JSON or RON strings. Here's what I mean:

```rust
use dust_dds::infrastructure::time::{Duration, DurationKind};

#[derive(serde::Serialize, serde::Deserialize, Debug)]
enum AltDurationKind {
    Finite(Duration),
    Infinite,
}

#[test]
fn duration_kind_serde() -> anyhow::Result<()> {
    let duration_kind = DurationKind::Finite(Duration::new(0, 0));
    let alt_duration_kind = AltDurationKind::Finite(Duration::new(0, 0));

    let serialized = bincode::serialize(&duration_kind)?;
    println!("bincode serialized normal: {serialized:?}");
    let result = bincode::deserialize::<DurationKind>(&serialized);
    println!("deserialized: {result:?}");

    let serialized = bincode::serialize(&alt_duration_kind)?;
    println!("bincode serialized alt: {serialized:?}");
    let result = bincode::deserialize::<AltDurationKind>(&serialized);
    println!("deserialized: {result:?}");

    let serialized = serde_json::to_string(&duration_kind)?;
    println!("json serialized normal: {serialized:?}");
    let result = serde_json::from_str::<DurationKind>(&serialized);
    println!("deserialized: {result:?}");

    let serialized = serde_json::to_string(&alt_duration_kind)?;
    println!("json serialized alt: {serialized:?}");
    let result = serde_json::from_str::<AltDurationKind>(&serialized);
    println!("deserialized: {result:?}");

    let serialized = ron::to_string(&duration_kind)?;
    println!("ron serialized normal: {serialized:?}");
    let result = ron::from_str::<DurationKind>(&serialized);
    println!("deserialized: {result:?}");

    let serialized = ron::to_string(&alt_duration_kind)?;
    println!("ron serialized alt: {serialized:?}");
    let result = ron::from_str::<AltDurationKind>(&serialized);
    println!("deserialized: {result:?}");

    Ok(())
}
```
Output:
```console
bincode serialized normal: [0, 0, 0, 0, 0, 0, 0, 0]
deserialized: Ok(Finite(Duration { sec: 0, nanosec: 0 }))
bincode serialized alt: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
deserialized: Ok(Finite(Duration { sec: 0, nanosec: 0 }))
json serialized normal: "{\"sec\":0,\"nanosec\":0}"
deserialized: Err(Error("invalid type: map, expected DurationKind", line: 1, column: 0))
json serialized alt: "{\"Finite\":{\"sec\":0,\"nanosec\":0}}"
deserialized: Ok(Finite(Duration { sec: 0, nanosec: 0 }))
ron serialized normal: "(sec:0,nanosec:0)"
deserialized: Err(SpannedError { code: ExpectedInteger, position: Position { line: 1, col: 2 } })
ron serialized alt: "Finite((sec:0,nanosec:0))"
deserialized: Ok(Finite(Duration { sec: 0, nanosec: 0 }))
```

I don't understand `serde` well enough to say how you could make `DurationKind` serialize/deserialize properly to/from in all cases. I think it has something to do with [how `serde` handles enums](https://serde.rs/enum-representations.html).

The only suggestion I have is to replace `DurationKind` with just `Duration` and use a constant for infinite duration instead, [like RustDDS does](https://github.com/jhelovuo/RustDDS/blob/a65f5bf234665f568b495c7f5c8db8dc56b4fb9f/src/structure/duration.rs#L87), but I realize this might seem less idiomatic than an enum.

EDIT: I've just noticed that `ReliabilityQosPolicyKind` (and possibly others?) has the same problem when deserializing with `serde_json`, but `ron` seems to work OK.

**Comment by jrebelo** [comment]
Hi @samcarey, this has likely to do with how the custom deserialization for the DurationKind is done here: https://github.com/s2e-systems/dust-dds/blob/62e62c345b59976f60c2685262a45c7f31c1970d/dds/src/dds/infrastructure/time.rs#L39.  The json deserializer is probably calling some method which is not implemented in our visitor or maybe expects something slightly different. Our implementation is done to comply with the CDR specification for this type so we can't really change it too much.

I believe the best way for you to solve this problem is to implement a From/Into between your AltDurationKind struct and DurationKind (possibly for the entire QoS structs). Then you use your struct for the serialize/deserialize part and convert it as needed to interface with DustDDS. The serialize/deserialize part of this DurationKind is not something standardized by DDS so this is also a trait bound that will be guaranteed as part of DustDDS to stay there.
