### ISSUE TITLE
Cyclone interoperability with data types

### ISSUE THREAD

**Issue by christianlulaj** [s2e-systems/dust-dds#292]
Cyclone DDS is not able to de-serialize a topic from dust dds that contains a struct as a field of the topic. 

Any help resolving this would be greatly appreciated

**Comment by jrebelo** [comment]
We have added a test to verify this and it seems to work without problems. Can you maybe give definition of the struct that you are using? Might be this is some corner case that we have not considered.

**Comment by christianlulaj** [comment]
## Here is the IDL file that I try using dust_dds_gen to generate from, the generated file comes with issues I have to manually resolve these, and after they are resolved cyclone can't even pick up the data from the dds bus. 

module School {
  typedef double M_Double;
  typedef int32_t M_Int32;
  typedef int64_t M_Int64;
  
  struct Student {
    M_Int32 studentID;
    M_Int32 studentPassPhrase;
  };

  struct Room {
    M_Int64 roomNumber;
    M_Int32 courseNumber;
  };
};

module MyUniversity {
  struct MyUniversityTopic {
    @key  School::Student student;
    School::Room room;
    School::M_Double age;
    School::Student student2;
    sequence<CommonStuff::Student,100> students;
    School::Student student3;
  };
};

**Comment by jrebelo** [comment]
Thank you for sharing your IDL. Which type are you publishing? Do you have a simple example of Dust DDS and Cyclone communicating in the system you are using? This is just to eliminate the option of this being a problem not at all related with the data.

There are also some errors in this IDL, in particular "int32_r" and "int64_t" are not recognized types in the IDL spec and the definition of the sequence is also not syntactically correct. The sharing of data between two modules is also something that I don't think is a good practice (and doesn't work at least in our case) since modules should be used to avoid name conflicts. So I modified it to the following and it compiles without problems:
module School {
            typedef double M_Double;
            typedef int32 M_Int32;
            typedef int64 M_Int64;

            struct Student {
                M_Int32 studentID;
                M_Int32 studentPassPhrase;
            };

            struct Room {
                M_Int64 roomNumber;
                M_Int32 courseNumber;
            };

            struct MyUniversityTopic {
                @key Student student;
                Room room;
                M_Double age;
                Student student2;
                sequence<Student,100> students;
                Student student3;
            };
        };
